version: "3.8"

services:
  documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs
    command: serve --dev-addr=0.0.0.0:8014 --watch-theme
    restart: unless-stopped
    ports:
      - "8014:8014"
    volumes:
      - ./documentation:/docs:ro

  database:
    image: postgres:16-alpine
    container_name: database
    hostname: database
    restart: always
    env_file:
      - .env
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - postgres_datastorage:/var/lib/postgresgl/data
    networks:
      - main_network

  backend_api:
    build:
      dockerfile: Dockerfile
      context: ./backend_api
    container_name: backend_api
    hostname: backend_api
    restart: always
    env_file:
      - .env
    ports:
      - "2323:2323"
    command: |
      sh -c "
      uvicorn main:app --port=2323 --host=0.0.0.0 --reload
      "
    networks:
      - main_network


networks:
  main_network:
    driver: bridge

volumes:
  postgres_datastorage:
    external: false